import ast
import json
from ollama import chat

# System prompt for the Developer Agent
SYSTEM_PROMPT = """
You are a Developer Agent for a robot navigation software system. 
Your goal is to write Python code based on the provided JSON navigation plan.
You MUST output ONLY valid Python code. Do not include any markdown formatting.
The code MUST contain a main function called `decide_next_move(state)`.
The 'state' dictionary will contain the following boolean keys: 
'goal_ahead', 'goal_on_left', 'goal_on_right', 'front_blocked', 'left_blocked', 'right_blocked'.
Use these exact keys to determine the next move (return "FORWARD", "LEFT", "RIGHT", or "STOP").
"""

# Function to validate the code generated by the Developer Agent
def validate_code(code_string):
    if not isinstance(code_string, str) or not code_string.strip():
        print("Validation Error: The output is empty or not a string.")
        return False
    
    # Use Python's built-in ast (Abstract Syntax Tree) to check if the code is syntactically valid
    try:
        ast.parse(code_string)
    except SyntaxError as e:
        print(f"Validation Error: Invalid Python syntax. {e}")
        return False
        
    # Check if the code actually defines any functions (must make sense for navigation)
    if "def " not in code_string:
        print("Validation Error: The code does not contain any function definitions.")
        return False
        
    return True

# Function to run the Developer Agent
def run_developer(plan):
    # Context Isolation: We ONLY pass the parsed plan.json to the Developer
    prompt_content = f"Here is the navigation plan from the Planner Agent:\n{json.dumps(plan)}\nWrite the Python code to implement this logic."
    
    print("Calling Qwen3:8b model via Ollama for Development...")
    response = chat(
        model="qwen3:8b", 
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt_content}
        ]
    )
    
    raw_content = response.message.content.strip()
    
    # Clean up the output in case Qwen adds markdown formatting despite the prompt
    if raw_content.startswith("```python"):
        raw_content = raw_content[9:-3].strip()
    elif raw_content.startswith("```"):
        raw_content = raw_content[3:-3].strip()
        
    if validate_code(raw_content):
        return raw_content
    else:
        print("Validation failed for the generated code.")
        print("Raw output was:\n", raw_content)
        return None