import json
from ollama import chat

## System prompt for the Planner Agent
## Describe its role, the expected output format, and the rules it must follow when generating a navigation plan.
## These are fairly similar to the Analyst Agent, but with a focus on creating a plan based on the requirements provided by the Analyst Agent.
SYSTEM_PROMPT = """
You are a Planner Agent for a robot navigation software system. 
Your goal is to decide how the software should behave based on the provided JSON requirements.
You MUST output your plan STRICTLY as a valid JSON object. Do not include any explanations, markdown code blocks (like ```json), or plain text outside of the JSON structure.

The JSON MUST contain exactly the following three keys:
1. "strategy for robot navigation": A string explaining your overall navigation strategy.
2. "a list of decisions": A list of strings representing the exact decisions the robot can take during navigation (e.g., ["FORWARD", "LEFT"]).
3. "the point at which the robot must stop": A string defining the exact condition or point for the robot to stop.
"""

## Function to validate the plan generated by the Planner Agent
## It should first check that the parameter it receives is of the correct type. 
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_plan(data):
    if not isinstance(data, dict):
        print("Validation Error: Input data must be a dictionary.")
        return False

    required_keys = ["strategy for robot navigation", "a list of decisions", "the point at which the robot must stop"]
    for key in required_keys:
        if key not in data:
            print(f"Validation Error: Missing key '{key}'.")
            return False
    if not isinstance(data["a list of decisions"], list):
        print("Validation Error: 'a list of decisions' must be a list.")
        return False
    return True


## Function to run the Planner Agent
## It takes the requirements generated by the Analyst Agent as input, sends them to the Planner Agent. Just like you did with the Analyst Agent.
## Take the response from the Planner Agent (Qwen), parse it and validate it using the validate_plan function, and return the validated plan.
def run_planner(requirement):
    prompt_content = f"Here are the validated requirements from the Analyst Agent:\n{json.dumps(requirement)}\nGenerate the navigation plan based on these requirements."
    print("Sending prompt to Planner Agent...")
    response = chat(
        model="qwen3:8b",
        messages=[{"role": "system", "content": SYSTEM_PROMPT},
                  {"role": "user", "content": prompt_content}]
    )
    raw_content = response.message.content.strip()
    if raw_content.startswith("```json"):
        raw_content = raw_content[7:-3].strip()
    elif raw_content.startswith("```"):
        raw_content = raw_content[3:-3].strip()
    try:
        plan_data = json.loads(raw_content)
        if validate_plan(plan_data):
            return plan_data
        else:
            print("Validation failed for the generated plan.")
            return None
    except json.JSONDecodeError as e:
        print(f"JSON decoding error: {e}")
        return None
    